///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDatabase.Image_Based
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ImageTesting recording.
    /// </summary>
    [TestModule("ef6c0f22-0a8d-4a71-a642-d5a970f5fc63", ModuleType.Recording, 1)]
    public partial class ImageTesting : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDatabase.RxDatabaseRepository repository.
        /// </summary>
        public static global::RxDatabase.RxDatabaseRepository repo = global::RxDatabase.RxDatabaseRepository.Instance;

        static ImageTesting instance = new ImageTesting();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ImageTesting()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ImageTesting Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.MonthCalendar1' at 10;7.", repo.DemoApplication.MonthCalendar1Info, new RecordItemIndex(0));
            repo.DemoApplication.MonthCalendar1.Click(new Location(MonthCalendar1_Screenshot2, "10;7", MonthCalendar1_Screenshot2_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.MonthCalendar1' at 10;5.", repo.DemoApplication.MonthCalendar1Info, new RecordItemIndex(1));
            repo.DemoApplication.MonthCalendar1.Click(new Location(MonthCalendar1_Screenshot3, "10;5", MonthCalendar1_Screenshot3_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApplication.MonthCalendar1' at 8;6.", repo.DemoApplication.MonthCalendar1Info, new RecordItemIndex(2));
            repo.DemoApplication.MonthCalendar1.Click(new Location(MonthCalendar1_Screenshot4, "8;6", MonthCalendar1_Screenshot4_Options));
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage MonthCalendar1_Screenshot2
        { get { return repo.DemoApplication.MonthCalendar1Info.GetScreenshot2(new Rectangle(126, 97, 14, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions MonthCalendar1_Screenshot2_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage MonthCalendar1_Screenshot3
        { get { return repo.DemoApplication.MonthCalendar1Info.GetScreenshot3(new Rectangle(157, 95, 14, 13)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions MonthCalendar1_Screenshot3_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage MonthCalendar1_Screenshot4
        { get { return repo.DemoApplication.MonthCalendar1Info.GetScreenshot4(new Rectangle(188, 97, 14, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions MonthCalendar1_Screenshot4_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
