///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDatabaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
    public partial class RxDatabaseRepository : RepoGenBaseFolder
    {
        static RxDatabaseRepository instance = new RxDatabaseRepository();
        RxDatabaseRepositoryFolders.DemoApplicationAppFolder _demoapplication;
        RxDatabaseRepositoryFolders.DepartmentListAppFolder _departmentlist;
        RxDatabaseRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the RxDatabaseRepository element repository.
        /// </summary>
        [RepositoryFolder("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
        public static RxDatabaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDatabaseRepository() 
            : base("RxDatabaseRepository", "/", null, 0, false, "7ed330c8-5668-4cfa-9ca9-402c4c23b7e2", ".\\RepositoryImages\\RxDatabaseRepository7ed330c8.rximgres")
        {
            _demoapplication = new RxDatabaseRepositoryFolders.DemoApplicationAppFolder(this);
            _departmentlist = new RxDatabaseRepositoryFolders.DepartmentListAppFolder(this);
            _explorer = new RxDatabaseRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

        string _lstDepartment = "Project Management";

        /// <summary>
        /// Gets or sets the value of variable lstDepartment.
        /// </summary>
        [TestVariable("99f51f25-dbe6-4edc-b8a7-dbc59c557c9b")]
        public string lstDepartment
        {
            get { return _lstDepartment; }
            set { _lstDepartment = value; }
        }

        string _setGender = "rdb Male";

        /// <summary>
        /// Gets or sets the value of variable setGender.
        /// </summary>
        [TestVariable("1a3a6e06-d4ec-47f8-8bea-e0c1d9c89480")]
        public string setGender
        {
            get { return _setGender; }
            set { _setGender = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DemoApplication folder.
        /// </summary>
        [RepositoryFolder("90b14745-bf25-4b07-9bb2-d31f69970826")]
        public virtual RxDatabaseRepositoryFolders.DemoApplicationAppFolder DemoApplication
        {
            get { return _demoapplication; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("57208867-ed11-4ec8-924b-0dc686980a77")]
        public virtual RxDatabaseRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("42ef1b13-1e7e-49a4-9b5a-290f7144ff35")]
        public virtual RxDatabaseRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDatabaseRepositoryFolders
    {
        /// <summary>
        /// The DemoApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("90b14745-bf25-4b07-9bb2-d31f69970826")]
        public partial class DemoApplicationAppFolder : RepoGenBaseFolder
        {
            RxDatabaseRepositoryFolders.DatabaseTabFolder _databasetab;
            RxDatabaseRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            RepoItemInfo _databaseInfo;
            RepoItemInfo _btnexitInfo;
            RepoItemInfo _imagebasedautomationInfo;
            RepoItemInfo _chkshowimageInfo;
            TheCatInfoClass _thecatInfo;
            MonthCalendar1InfoClass _monthcalendar1Info;

            /// <summary>
            /// Creates a new DemoApplication  folder.
            /// </summary>
            public DemoApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoApplication", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "90b14745-bf25-4b07-9bb2-d31f69970826", "")
            {
                _databasetab = new RxDatabaseRepositoryFolders.DatabaseTabFolder(this);
                _rxtabintroduction = new RxDatabaseRepositoryFolders.RxTabIntroductionFolder(this);
                _databaseInfo = new RepoItemInfo(this, "Database", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "34b9f228-153b-44b4-ae34-1e2747592b0f");
                _btnexitInfo = new RepoItemInfo(this, "BtnExit", "button[@controlname='RxButtonExit']", "", 30000, null, "02058d54-efaf-4a1d-b09d-9d7d8538364d");
                _imagebasedautomationInfo = new RepoItemInfo(this, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", "", 30000, null, "c535ddc7-a10e-48c5-aed5-1282bc8b0bfb");
                _chkshowimageInfo = new RepoItemInfo(this, "ChkShowImage", "?/?/tabpage[@controlname='RxTabImageBased']/checkbox[@controlname='chkShowImage']", "", 30000, null, "698e5cbd-9aca-490d-b65a-450401f784fb");
                _thecatInfo = new TheCatInfoClass(this);
                _monthcalendar1Info = new MonthCalendar1InfoClass(this);
            }

            /// <summary>
            /// The TheCatInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("4c02302e-657c-46f6-9708-6374bdc5e6ef")]
            public class TheCatInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TheCatInfoClass class constructor.
                /// </summary>
                public TheCatInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TheCat", "?/?/tabpage[@controlname='RxTabImageBased']/picture[@controlname='TheCat']", 30000, null, "4c02302e-657c-46f6-9708-6374bdc5e6ef")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("c815aa9a-7e54-4cd1-bf10-623b89d65c76")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("c815aa9a-7e54-4cd1-bf10-623b89d65c76");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c815aa9a-7e54-4cd1-bf10-623b89d65c76")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c815aa9a-7e54-4cd1-bf10-623b89d65c76", cropRect);
                }
            }

            /// <summary>
            /// The MonthCalendar1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("708afefd-c3ba-4247-92dc-82f80a498eb6")]
            public class MonthCalendar1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// MonthCalendar1InfoClass class constructor.
                /// </summary>
                public MonthCalendar1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "MonthCalendar1", "?/?/tabpage[@controlname='RxTabImageBased']/datetime[@controlname='monthCalendar1']", 30000, null, "708afefd-c3ba-4247-92dc-82f80a498eb6")
                { }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("3a377804-1a8d-4d76-93a1-967d6691e1de")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("3a377804-1a8d-4d76-93a1-967d6691e1de");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3a377804-1a8d-4d76-93a1-967d6691e1de")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3a377804-1a8d-4d76-93a1-967d6691e1de", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("65cb7ffb-bf3e-48d1-a549-559f55624762")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("65cb7ffb-bf3e-48d1-a549-559f55624762");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("65cb7ffb-bf3e-48d1-a549-559f55624762")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("65cb7ffb-bf3e-48d1-a549-559f55624762", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("1dbc797d-2e5b-461e-aae6-1cd55c12457c")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("1dbc797d-2e5b-461e-aae6-1cd55c12457c");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("1dbc797d-2e5b-461e-aae6-1cd55c12457c")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("1dbc797d-2e5b-461e-aae6-1cd55c12457c", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("90b14745-bf25-4b07-9bb2-d31f69970826")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("90b14745-bf25-4b07-9bb2-d31f69970826")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Database item.
            /// </summary>
            [RepositoryItem("34b9f228-153b-44b4-ae34-1e2747592b0f")]
            public virtual Ranorex.TabPage Database
            {
                get
                {
                    return _databaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Database item info.
            /// </summary>
            [RepositoryItemInfo("34b9f228-153b-44b4-ae34-1e2747592b0f")]
            public virtual RepoItemInfo DatabaseInfo
            {
                get
                {
                    return _databaseInfo;
                }
            }

            /// <summary>
            /// The BtnExit item.
            /// </summary>
            [RepositoryItem("02058d54-efaf-4a1d-b09d-9d7d8538364d")]
            public virtual Ranorex.Button BtnExit
            {
                get
                {
                    return _btnexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnExit item info.
            /// </summary>
            [RepositoryItemInfo("02058d54-efaf-4a1d-b09d-9d7d8538364d")]
            public virtual RepoItemInfo BtnExitInfo
            {
                get
                {
                    return _btnexitInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("c535ddc7-a10e-48c5-aed5-1282bc8b0bfb")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("c535ddc7-a10e-48c5-aed5-1282bc8b0bfb")]
            public virtual RepoItemInfo ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("698e5cbd-9aca-490d-b65a-450401f784fb")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("698e5cbd-9aca-490d-b65a-450401f784fb")]
            public virtual RepoItemInfo ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The TheCat item.
            /// </summary>
            [RepositoryItem("4c02302e-657c-46f6-9708-6374bdc5e6ef")]
            public virtual Ranorex.Picture TheCat
            {
                get
                {
                    return _thecatInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The TheCat item info.
            /// </summary>
            [RepositoryItemInfo("4c02302e-657c-46f6-9708-6374bdc5e6ef")]
            public virtual TheCatInfoClass TheCatInfo
            {
                get
                {
                    return _thecatInfo;
                }
            }

            /// <summary>
            /// The MonthCalendar1 item.
            /// </summary>
            [RepositoryItem("708afefd-c3ba-4247-92dc-82f80a498eb6")]
            public virtual Ranorex.DateTime MonthCalendar1
            {
                get
                {
                    return _monthcalendar1Info.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The MonthCalendar1 item info.
            /// </summary>
            [RepositoryItemInfo("708afefd-c3ba-4247-92dc-82f80a498eb6")]
            public virtual MonthCalendar1InfoClass MonthCalendar1Info
            {
                get
                {
                    return _monthcalendar1Info;
                }
            }

            /// <summary>
            /// The DatabaseTab folder.
            /// </summary>
            [RepositoryFolder("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual RxDatabaseRepositoryFolders.DatabaseTabFolder DatabaseTab
            {
                get { return _databasetab; }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("243704a2-65ce-48f8-9bf4-c776006fedd6")]
            public virtual RxDatabaseRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The DatabaseTabFolder folder.
        /// </summary>
        [RepositoryFolder("6634980e-930f-41f9-a6d0-229595c55fed")]
        public partial class DatabaseTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _selectmaleInfo;
            RepoItemInfo _btndepartmentlistInfo;
            RepoItemInfo _btnaddentryInfo;
            RepoItemInfo _counterentriesInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _grpgenderInfo;
            RepoItemInfo _rdbfemaleInfo;

            /// <summary>
            /// Creates a new DatabaseTab  folder.
            /// </summary>
            public DatabaseTabFolder(RepoGenBaseFolder parentFolder) :
                    base("DatabaseTab", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "6634980e-930f-41f9-a6d0-229595c55fed", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "ee66a06e-163b-42b6-8abc-248006bf88ab");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "305b1e85-498e-4d07-9051-6cd79362827e");
                _selectmaleInfo = new RepoItemInfo(this, "SelectMale", "?/?/radiobutton[@controlname=$setGender]", "", 30000, null, "a47a714c-11a3-4925-b181-0c2445fd1e45");
                _btndepartmentlistInfo = new RepoItemInfo(this, "BtnDepartmentList", "combobox[@controlname='cmbDepartment']/button", "", 30000, null, "33397b0b-43c6-4daa-99a2-c7853656f16f");
                _btnaddentryInfo = new RepoItemInfo(this, "BtnAddEntry", "button[@controlname='btnAddPerson']", "", 30000, null, "0716c660-ce8c-4fb8-a033-a58ae01bc4fa");
                _counterentriesInfo = new RepoItemInfo(this, "CounterEntries", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "2580fade-1b69-498e-a86e-74c7c8e8be71");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controlname=$setGender]", "", 30000, null, "b9fb3111-d561-48ba-a808-eb7dcbe36e23");
                _grpgenderInfo = new RepoItemInfo(this, "GrpGender", "container[@controlname='grpGender']", "", 30000, null, "38d5f788-d43b-477f-8095-bce3c68de318");
                _rdbfemaleInfo = new RepoItemInfo(this, "RdbFemale", "?/?/radiobutton[@controlname='rdbFemale']", "", 30000, null, "1a14d82c-f087-4ea2-a58e-eba05c07af17");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("ee66a06e-163b-42b6-8abc-248006bf88ab")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("ee66a06e-163b-42b6-8abc-248006bf88ab")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("305b1e85-498e-4d07-9051-6cd79362827e")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("305b1e85-498e-4d07-9051-6cd79362827e")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The SelectMale item.
            /// </summary>
            [RepositoryItem("a47a714c-11a3-4925-b181-0c2445fd1e45")]
            public virtual Ranorex.RadioButton SelectMale
            {
                get
                {
                    return _selectmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SelectMale item info.
            /// </summary>
            [RepositoryItemInfo("a47a714c-11a3-4925-b181-0c2445fd1e45")]
            public virtual RepoItemInfo SelectMaleInfo
            {
                get
                {
                    return _selectmaleInfo;
                }
            }

            /// <summary>
            /// The BtnDepartmentList item.
            /// </summary>
            [RepositoryItem("33397b0b-43c6-4daa-99a2-c7853656f16f")]
            public virtual Ranorex.Button BtnDepartmentList
            {
                get
                {
                    return _btndepartmentlistInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDepartmentList item info.
            /// </summary>
            [RepositoryItemInfo("33397b0b-43c6-4daa-99a2-c7853656f16f")]
            public virtual RepoItemInfo BtnDepartmentListInfo
            {
                get
                {
                    return _btndepartmentlistInfo;
                }
            }

            /// <summary>
            /// The BtnAddEntry item.
            /// </summary>
            [RepositoryItem("0716c660-ce8c-4fb8-a033-a58ae01bc4fa")]
            public virtual Ranorex.Button BtnAddEntry
            {
                get
                {
                    return _btnaddentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddEntry item info.
            /// </summary>
            [RepositoryItemInfo("0716c660-ce8c-4fb8-a033-a58ae01bc4fa")]
            public virtual RepoItemInfo BtnAddEntryInfo
            {
                get
                {
                    return _btnaddentryInfo;
                }
            }

            /// <summary>
            /// The CounterEntries item.
            /// </summary>
            [RepositoryItem("2580fade-1b69-498e-a86e-74c7c8e8be71")]
            public virtual Ranorex.Text CounterEntries
            {
                get
                {
                    return _counterentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CounterEntries item info.
            /// </summary>
            [RepositoryItemInfo("2580fade-1b69-498e-a86e-74c7c8e8be71")]
            public virtual RepoItemInfo CounterEntriesInfo
            {
                get
                {
                    return _counterentriesInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("b9fb3111-d561-48ba-a808-eb7dcbe36e23")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("b9fb3111-d561-48ba-a808-eb7dcbe36e23")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The GrpGender item.
            /// </summary>
            [RepositoryItem("38d5f788-d43b-477f-8095-bce3c68de318")]
            public virtual Ranorex.Container GrpGender
            {
                get
                {
                    return _grpgenderInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GrpGender item info.
            /// </summary>
            [RepositoryItemInfo("38d5f788-d43b-477f-8095-bce3c68de318")]
            public virtual RepoItemInfo GrpGenderInfo
            {
                get
                {
                    return _grpgenderInfo;
                }
            }

            /// <summary>
            /// The RdbFemale item.
            /// </summary>
            [RepositoryItem("1a14d82c-f087-4ea2-a58e-eba05c07af17")]
            public virtual Ranorex.RadioButton RdbFemale
            {
                get
                {
                    return _rdbfemaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbFemale item info.
            /// </summary>
            [RepositoryItemInfo("1a14d82c-f087-4ea2-a58e-eba05c07af17")]
            public virtual RepoItemInfo RdbFemaleInfo
            {
                get
                {
                    return _rdbfemaleInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("243704a2-65ce-48f8-9bf4-c776006fedd6")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "243704a2-65ce-48f8-9bf4-c776006fedd6", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", "", 30000, null, "10fa2329-3aa7-4d28-8fed-e28686640c66");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", "", 30000, null, "426d636b-3536-4fc5-8263-875d7fa25a9b");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", "", 30000, null, "a44ee35f-0ed7-4f96-81d7-17f0ebdb8df3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("243704a2-65ce-48f8-9bf4-c776006fedd6")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("243704a2-65ce-48f8-9bf4-c776006fedd6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("10fa2329-3aa7-4d28-8fed-e28686640c66")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("10fa2329-3aa7-4d28-8fed-e28686640c66")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("426d636b-3536-4fc5-8263-875d7fa25a9b")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("426d636b-3536-4fc5-8263-875d7fa25a9b")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("a44ee35f-0ed7-4f96-81d7-17f0ebdb8df3")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("a44ee35f-0ed7-4f96-81d7-17f0ebdb8df3")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("57208867-ed11-4ec8-924b-0dc686980a77")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "57208867-ed11-4ec8-924b-0dc686980a77", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text=$lstDepartment]", "", 30000, null, "b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("57208867-ed11-4ec8-924b-0dc686980a77")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("57208867-ed11-4ec8-924b-0dc686980a77")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("42ef1b13-1e7e-49a4-9b5a-290f7144ff35")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rxtestapp101runningwindowInfo;
            TrayClockWClassInfoClass _trayclockwclassInfo;
            TrayShowDesktopButtonWClassInfoClass _trayshowdesktopbuttonwclassInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "42ef1b13-1e7e-49a4-9b5a-290f7144ff35", "")
            {
                _rxtestapp101runningwindowInfo = new RepoItemInfo(this, "RXTestApp101RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[8]", "", 30000, null, "22aebb52-ccfe-4ad5-980a-51e4e7f95d72");
                _trayclockwclassInfo = new TrayClockWClassInfoClass(this);
                _trayshowdesktopbuttonwclassInfo = new TrayShowDesktopButtonWClassInfoClass(this);
            }

            /// <summary>
            /// The TrayClockWClassInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("a826abf2-b637-409a-9731-45194c35f405")]
            public class TrayClockWClassInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TrayClockWClassInfoClass class constructor.
                /// </summary>
                public TrayClockWClassInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TrayClockWClass", "?/?/text[@class='TrayClockWClass']", 30000, null, "a826abf2-b637-409a-9731-45194c35f405")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("fccfe77d-1eda-4aa4-92c2-1ecb5b9ad789")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("fccfe77d-1eda-4aa4-92c2-1ecb5b9ad789");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("fccfe77d-1eda-4aa4-92c2-1ecb5b9ad789")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("fccfe77d-1eda-4aa4-92c2-1ecb5b9ad789", cropRect);
                }
            }

            /// <summary>
            /// The TrayShowDesktopButtonWClassInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("d8fddbc3-148d-42b9-9794-afa09855ea1e")]
            public class TrayShowDesktopButtonWClassInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TrayShowDesktopButtonWClassInfoClass class constructor.
                /// </summary>
                public TrayShowDesktopButtonWClassInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TrayShowDesktopButtonWClass", "?/?/button[@controlid='307']", 30000, null, "d8fddbc3-148d-42b9-9794-afa09855ea1e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("4fb89dfb-a37d-441c-adbc-1a01047ec4ce")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("4fb89dfb-a37d-441c-adbc-1a01047ec4ce");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("4fb89dfb-a37d-441c-adbc-1a01047ec4ce")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("4fb89dfb-a37d-441c-adbc-1a01047ec4ce", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42ef1b13-1e7e-49a4-9b5a-290f7144ff35")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42ef1b13-1e7e-49a4-9b5a-290f7144ff35")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RXTestApp101RunningWindow item.
            /// </summary>
            [RepositoryItem("22aebb52-ccfe-4ad5-980a-51e4e7f95d72")]
            public virtual Ranorex.Button RXTestApp101RunningWindow
            {
                get
                {
                    return _rxtestapp101runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RXTestApp101RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("22aebb52-ccfe-4ad5-980a-51e4e7f95d72")]
            public virtual RepoItemInfo RXTestApp101RunningWindowInfo
            {
                get
                {
                    return _rxtestapp101runningwindowInfo;
                }
            }

            /// <summary>
            /// The TrayClockWClass item.
            /// </summary>
            [RepositoryItem("a826abf2-b637-409a-9731-45194c35f405")]
            public virtual Ranorex.Text TrayClockWClass
            {
                get
                {
                    return _trayclockwclassInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TrayClockWClass item info.
            /// </summary>
            [RepositoryItemInfo("a826abf2-b637-409a-9731-45194c35f405")]
            public virtual TrayClockWClassInfoClass TrayClockWClassInfo
            {
                get
                {
                    return _trayclockwclassInfo;
                }
            }

            /// <summary>
            /// The TrayShowDesktopButtonWClass item.
            /// </summary>
            [RepositoryItem("d8fddbc3-148d-42b9-9794-afa09855ea1e")]
            public virtual Ranorex.Button TrayShowDesktopButtonWClass
            {
                get
                {
                    return _trayshowdesktopbuttonwclassInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TrayShowDesktopButtonWClass item info.
            /// </summary>
            [RepositoryItemInfo("d8fddbc3-148d-42b9-9794-afa09855ea1e")]
            public virtual TrayShowDesktopButtonWClassInfoClass TrayShowDesktopButtonWClassInfo
            {
                get
                {
                    return _trayshowdesktopbuttonwclassInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
