///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDatabase.Error_behavior
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidationMessage recording.
    /// </summary>
    [TestModule("51b87966-acff-4f59-9950-79669c599902", ModuleType.Recording, 1)]
    public partial class ValidationMessage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDatabase.RxDatabaseRepository repository.
        /// </summary>
        public static global::RxDatabase.RxDatabaseRepository repo = global::RxDatabase.RxDatabaseRepository.Instance;

        static ValidationMessage instance = new ValidationMessage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidationMessage()
        {
            LblMessage = "Welcome, mario!";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidationMessage Instance
        {
            get { return instance; }
        }

#region Variables

        string _LblMessage;

        /// <summary>
        /// Gets or sets the value of variable LblMessage.
        /// </summary>
        [TestVariable("44c23266-270f-4dce-b5f4-68553de4c638")]
        public string LblMessage
        {
            get { return _LblMessage; }
            set { _LblMessage = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'ControlText' from item 'DemoApplication.RxTabIntroduction.LblWelcomeMessage' and assigning its value to variable 'LblMessage'.", repo.DemoApplication.RxTabIntroduction.LblWelcomeMessageInfo, new RecordItemIndex(0));
            LblMessage = repo.DemoApplication.RxTabIntroduction.LblWelcomeMessage.Element.GetAttributeValueText("ControlText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$LblMessage) on item 'DemoApplication.RxTabIntroduction.LblWelcomeMessage'.", repo.DemoApplication.RxTabIntroduction.LblWelcomeMessageInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.DemoApplication.RxTabIntroduction.LblWelcomeMessageInfo, "Text", LblMessage);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
